### ISSUE TITLE
Couldn't make it work

### ISSUE THREAD

**Issue by dvdrbls** [thi-ng/vexed-generation#1]
Hi Im using houdini 16.0.21 and I have this error following all your steps

Error | The sub-network output operator failed to cook: /obj/grid1/pointwrangle1/attribvop1Warning: Errors or warnings encountered during VEX compile:/obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1).Errors or warnings encountered during VEX compile:/obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1).Errors or warnings encountered during VEX compile:/obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1).Errors or warnings encountered during VEX compile:/obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1).Errors or warnings encountered during VEX compile:/obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1).Errors or warnings encountered during VEX compile:/obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1).Errors or warnings encountered during VEX compile:/obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1).Errors or warnings encountered during VEX compile:/obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1).Errors or warnings encountered during VEX compile:/obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1).Error: Vex error: /obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1)Failed to resolve VEX code op:/obj/grid1/pointwrangle1/attribvop1Unable to load shader 'op:/obj/grid1/pointwrangle1/attribvop1'.
-- | --
Warning | Errors or warnings encountered during VEX compile:/obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1).
Warning | Errors or warnings encountered during VEX compile:/obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1).
Warning | Errors or warnings encountered during VEX compile:/obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1).
Warning | Errors or warnings encountered during VEX compile:/obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1).
Warning | Errors or warnings encountered during VEX compile:/obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1).
Warning | Errors or warnings encountered during VEX compile:/obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1).
Warning | Errors or warnings encountered during VEX compile:/obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1).
Warning | Errors or warnings encountered during VEX compile:/obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1).
Warning | Errors or warnings encountered during VEX compile:/obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1).
Warning | Vex error: /obj/grid1/pointwrangle1/attribvop1: Unable to include (21,1)Failed to resolve VEX code op:/obj/grid1/pointwrangle1/attribvop1Unable to load shader 'op:/obj/grid1/pointwrangle1/attribvop1'

what can I do?
Thank you

**Comment by postspectacular** [comment]
Hi @dvdrbls - sorry you're having issues with this, can I ask:

1) Which OS are you using?
2) Did you add/edit the `HOUDINI_VEX_PATH` env variable **prior** to starting Houdini?

Can you please switch to the "Technical desktop" and type this in the Python shell?

```python
hou.getenv("HOUDINI_VEX_PATH")
```

Does it return a string which includes the vgen path?

**Comment by dvdrbls** [comment]
Hi, I'm using windows 10 
Python 2.7.5 (default, Nov  6 2016, 12:19:41) [MSC v.1900 64 bit (AMD64)] on win32
Houdini 16.0.621 hou module imported.
Type "help", "copyright", "credits" or "license" for more information.
>>> hou.getenv("HOUDINI_VEX_PATH")
'C:/Users/DELL/vexed-generation/opencl;&;'
>>> 

this are the lines I added to the Houdini.env
HOUDINI_VEX_PATH = C:\Users\DELL\vexed-generation\opencl;&;
HOUDINI_OCL_PATH = C:\Users\DELL\vexed-generation\vex;&;

and this is the route where the git command put the files C:\Users\DELL\vexed-generation
I'm a novice in Houdini but i really want to make it work

Thanks again

**Comment by dvdrbls** [comment]
Right in the path was the mistake I made, it is working
Thank you

**Comment by postspectacular** [comment]
Oki, phew... :) @dvdrbls would you mind sharing what was wrong with the path? it looked fine to me, but I'm on OSX so maybe there's some Windows thing I should mention in the readme?

**Comment by dvdrbls** [comment]
It was reversed the order, my bad not yours
bad =  HOUDINI_VEX_PATH = C:\Users\DELL\vexed-generation\opencl;&;
bad = HOUDINI_OCL_PATH = C:\Users\DELL\vexed-generation\vex;&;

HOUDINI_VEX_PATH = C:\Users\DELL\vexed-generation\vex;&;
HOUDINI_OCL_PATH = C:\Users\DELL\vexed-generation\opencl;&;

As you can see it was a pretty simple mistake of mine 
![Annotation 2019-04-29 155429](https://user-images.githubusercontent.com/5351941/56926373-50388c80-6a97-11e9-887f-c2e48ba517c3.jpg)

**Comment by postspectacular** [comment]
Hah! Thanks, indeed that was one of those things too trivial to notice :) Glad it worked. Btw. I will add some more example files in the near future, but be sure to also check this repo: https://github.com/thi-ng/houdini/
